repos:
- repo: local
  hooks:
    - id: isort
      name: run isort
      entry: isort
      verbose: true
      language: system
    - id: ruff
      name: ruff check run
      entry: ruff check
      verbose: true
      args: [ --fix ]
      language: python